version: "3.8"

services:
  bot_db:
    image: postgres:latest
    container_name: bot_db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: bookbot
      POSTGRES_USER: bookbot
      POSTGRES_DB: bookbot
      POSTGRES_ROOT_PASSWORD: root
    ports:
        - "5432:5432"
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ACCESS_KEY: longerthan5
      MINIO_SECRET_KEY: longerthan8
      MINIO_ROOT_USER: longroot
      MINIO_ROOT_PASSWORD: longerrootpassword
    ports:
      - "9000:9000"
      - "9090:9090"
    command: server /data --console-address ":9090"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 20s
      retries: 3

  create_buckets:
    image: minio/mc:latest
    container_name: createbuckets
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      mc config host add myminio http://minio:9000 longerthan5 longerthan8 &&
      mc mb myminio/bookbot &&
      mc anonymous set policy download myminio/bookbot
      "
      
