version: "3.8"

services:
  bot_db:
    image: postgres:latest
    container_name: bot_db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: bookbot
      POSTGRES_USER: bookbot
      POSTGRES_DB: bookbot
      POSTGRES_ROOT_PASSWORD: root
    ports:
        - "5432:5432"