version: "3.8"

services:
  bot_db:
    image: postgres:latest
    container_name: bot_db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: bookbot
      POSTGRES_USER: bookbot
      POSTGRES_DB: bookbot
      POSTGRES_ROOT_PASSWORD: root
    ports:
        - "5433:5433"
  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: derpz-discord/math-tavern-bot:latest
    container_name: math-tavern-bot
    restart: unless-stopped
    env_file:
      - .env

  sully_worker_1:
    build:
      context: .
      dockerfile: Dockerfile
    image: derpz-discord/autosully-worker:latest
    container_name: sully_worker_1
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - WORKER_NUMBER=1
    entrypoint: python sully_worker.py
    depends_on:
      - bot_db
      - redis

  sully_worker_2:
    build:
      context: .
      dockerfile: Dockerfile
    image: derpz-discord/autosully-worker:latest
    container_name: sully_worker_2
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - WORKER_NUMBER=2
    entrypoint: python sully_worker.py
    depends_on:
      - bot_db
      - redis